### ISSUE TITLE
Can I use this to exchange Ethereum against any other stable currency?

### ISSUE THREAD

**Issue by Kremed** [Nethereum/Nethereum.Uniswap-V2-and-V3#7]
Now after creating an Ethereum wallet, we need to create a process to exchange Ethereum for tokens, according to the review, we found that the uniswap protocol must be dealt with. Is this repository to deal with the uniswap protocol!!

If it is possible to provide us with the necessary documentation for this process or any examples using Nethereum

**Comment by juanfranblanco** [comment]
Check the unit tests here https://github.com/Nethereum/Nethereum.Uniswap-V2-and-V3/blob/main/Nethereum.Uniswap.Testing/UniSwapV2PairTests.cs

**Comment by Kremed** [comment]
Sorry for the inconvenience, the addresses of the contracts in the test layer are such as :
```
//Unswap smart contract Address !? 
var routerV2Address = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D";
//weth smart contract Address !? 
var weth = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2";
//Dai smart contract Address !? 
var dai = "0x6b175474e89094c44da98b954eedeac495271d0f";
```

These addresses are smart contract addresses on the mainnet, right?
I think I need to find them On the test network Ropsten??
Is that correct ??

**Comment by juanfranblanco** [comment]
Yes, this is using mainnet testing as a fork. If you want to work in ropsten it will be different. Use this to get some test weth if needed https://faucet.paradigm.xyz/
